server:
  port: 8081

spring:
  application:
    name: sentinelDemo
  profiles:
    active: log
  aop:
    proxy-target-class: true
  main:
    allow-circular-references: true

  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      datasource:
        ds:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-sentinel
            groupId: DEFAULT_GROUP
            rule-type: flow
