spring:
  task:
    execution:
      thread-name-prefix: FundTask-
      pool:
        allow-core-thread-timeout: true
        core-size: 10
        keep-alive: 60s
        max-size: 20
        queue-capacity: 20000
